services:
  app:
    build: .
    container_name: eat-right
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000
    volumes:
      - .:/app
    env_file:
      - .env
  